HearthSim/HSTracker

config/locales/en.yml
=> English Localization updates

config/locales/pt-br.yml
Since the number of brazilian players are increasing, this translation can help those who don't know any language that HSTracker supports.
=> Add pt-br language

app/hearthstone/game.rb
=> Fixing typo

config/locales/en.yml
Thought that the `Save match` was a little ambiguous. :smile:
=> Update language a bit

HSTracker/UIs/Preferences/de.lproj/TrackersPreferences.strings
=> WIP wording

HSTracker/Database/Models/Deck.swift
=> Replace int division with float division in computing winrate for display

HSTracker/AppDelegate.swift, HSTracker/UIs/Base.lproj/MainMenu.xib, HSTracker/UIs/DeckManager/DeckManager.swift
Save your current deck in the tracker.
=> Save your current deck in the tracker

HSTracker/AppDelegate.swift
=> move save items into submenu for cleanliness

HSTracker/UIs/DeckManager/Base.lproj/NewDeck.xib, HSTracker/UIs/DeckManager/DeckManager.swift, HSTracker/UIs/DeckManager/NewDeck.swift
1. Type in class name when creating new deck
2. If you have a filtered deck, new deck creation will default to that class
=> Two features in #342

HSTracker/UIs/Cards/MinimalBar.swift
Just a typo fix. (And learning git.)
=> spelling "guassian" -> "gaussian"

HSTracker/Base.lproj/Localizable.strings, HSTracker/UIs/DeckManager/EditDeck.swift, HSTracker/de.lproj/Localizable.strings, HSTracker/es.lproj/Localizable.strings, HSTracker/fr.lproj/Localizable.strings, HSTracker/it.lproj/Localizable.strings, HSTracker/pt-BR.lproj/Localizable.strings, HSTracker/zh-Hans.lproj/Localizable.strings
I removed the event monitor for 'z'. I think that should be okay.
=> Undo/redo while editing deck #346

HSTracker/Base.lproj/Localizable.strings, HSTracker/Core/Settings.swift, HSTracker/Database/Models/Deck.swift, HSTracker/UIs/DeckManager/Base.lproj/DeckManager.xib, HSTracker/UIs/DeckManager/DeckManager.swift, HSTracker/UIs/DeckManager/de.lproj/DeckManager.strings, HSTracker/UIs/DeckManager/es.lproj/DeckManager.strings, HSTracker/UIs/DeckManager/fr.lproj/DeckManager.strings, HSTracker/UIs/DeckManager/it.lproj/DeckManager.strings, HSTracker/UIs/DeckManager/pt-BR.lproj/DeckManager.strings, HSTracker/UIs/DeckManager/zh-Hans.lproj/DeckManager.strings, HSTracker/de.lproj/Localizable.strings, HSTracker/es.lproj/Localizable.strings, HSTracker/fr.lproj/Localizable.strings, HSTracker/it.lproj/Localizable.strings, HSTracker/pt-BR.lproj/Localizable.strings, HSTracker/zh-Hans.lproj/Localizable.strings
Sort deck manager, as requested here:
#345
=> Sort deck manager

HSTracker/UIs/DeckManager/DeckCellView.swift, HSTracker/UIs/DeckManager/DeckCellView.xib, HSTracker/UIs/DeckManager/DeckManager.swift
Wild indicator for decks, but no asset
=> Wild indicator for decks, but no asset

HSTracker/UIs/Preferences/zh-Hans.lproj/GeneralPreferences.strings, HSTracker/UIs/Preferences/zh-Hans.lproj/OpponentTrackersPreferences.strings, HSTracker/UIs/Preferences/zh-Hans.lproj/PlayerTrackersPreferences.strings, HSTracker/UIs/Preferences/zh-Hans.lproj/TrackersPreferences.strings, HSTracker/UIs/zh-Hans.lproj/MainMenu.strings, HSTracker/zh-Hans.lproj/Localizable.strings
Been busy during the past month. Love the new look.
=> A Long Awaited Update

HSTracker/Core/Settings.swift, HSTracker/Database/Cards.swift, HSTracker/UIs/Cards/CardBar.swift, HSTracker/UIs/Cards/MinimalBar.swift, HSTracker/UIs/Preferences/Base.lproj/PlayerTrackersPreferences.xib, HSTracker/UIs/Preferences/PlayerTrackersPreferences.swift, HSTracker/UIs/Preferences/de.lproj/PlayerTrackersPreferences.strings, HSTracker/UIs/Preferences/es.lproj/PlayerTrackersPreferences.strings, HSTracker/UIs/Preferences/fr.lproj/PlayerTrackersPreferences.strings, HSTracker/UIs/Preferences/it.lproj/PlayerTrackersPreferences.strings, HSTracker/UIs/Preferences/pt-BR.lproj/PlayerTrackersPreferences.strings, HSTracker/UIs/Preferences/zh-Hans.lproj/PlayerTrackersPreferences.strings, HSTracker/UIs/Trackers/Tracker.swift
https://github.com/bmichotte/HSTracker/issues/489
=> show deck name option

HSTracker/Statistics/StatsHelper.swift, HSTracker/UIs/StatsManager/Statistics.swift
=> Stats table sorts when headers are clicked

HSTracker.xcodeproj/project.pbxproj, HSTracker/AppDelegate.swift, HSTracker/Base.lproj/Localizable.strings, HSTracker/Logging/Draft.swift, HSTracker/Logging/Handlers/ArenaHandler.swift, HSTracker/Logging/Handlers/LoadingScreenHandler.swift, HSTracker/de.lproj/Localizable.strings, HSTracker/es.lproj/Localizable.strings, HSTracker/fr.lproj/Localizable.strings, HSTracker/it.lproj/Localizable.strings, HSTracker/pt-BR.lproj/Localizable.strings, HSTracker/zh-Hans.lproj/Localizable.strings
Replace https://github.com/bmichotte/HSTracker/pull/479
=> Import your arena deck

HSTracker/UIs/StatsManager/Base.lproj/LadderTab.xib, HSTracker/UIs/StatsManager/Base.lproj/StatsTab.xib, HSTracker/UIs/StatsManager/LadderTab.swift, HSTracker/UIs/StatsManager/Statistics.swift, HSTracker/UIs/StatsManager/StatsTab.swift
Attempt to fix "HSTracker.Statistics.update () -> ()" error.
Apparently, NSTableView.reloadData is not thread safe. This fix puts all data changes and reloadData calls in the main thread.
=> Fix stats race condition

HSTracker/Utility/RankDetection/CVRankDetection.swift, HSTracker/Utility/RankDetection/CVRankDetector.cpp, HSTracker/Utility/RankDetection/CVRankDetector.hpp, HSTracker/Utility/RankDetection/CVRankDetectorWrapper.hpp, HSTracker/Utility/RankDetection/CVRankDetectorWrapper.mm
* Added guards against the rank detection crash
* Added back in rank detection thresholding that were accidentally removed in 51e7c9e8c818b12212a73fb5e87ff2c011824de7
=> Fix rank detection crash?

HSTracker.xcodeproj/project.pbxproj, HSTracker/Base.lproj/Localizable.strings, HSTracker/Database/Cards.swift, HSTracker/Importers/Handlers/Hearthstonetopdecks.swift, HSTracker/Importers/NetImporter.swift, HSTracker/UIs/DeckManager/NewDeck.swift, HSTracker/de.lproj/Localizable.strings, HSTracker/es.lproj/Localizable.strings, HSTracker/fr.lproj/Localizable.strings, HSTracker/it.lproj/Localizable.strings, HSTracker/pt-BR.lproj/Localizable.strings, HSTracker/zh-Hans.lproj/Localizable.strings
Added deck importer from hearthstonetopdeck.com
Added an error message dialog when deck import fails
=> hearthstonetopdeck.com deck importer

HSTracker/Importers/BaseNetImporter.swift, HSTracker/Importers/Handlers/Heartharena.swift, HSTracker/UIs/Trackers/BoardDamage.swift, HSTracker/UIs/Trackers/BoardDamage.xib, HSTracker/UIs/Trackers/CardHudContainer.swift, HSTracker/UIs/Trackers/CardHudContainer.xib, HSTracker/UIs/Trackers/SecretTracker.swift, HSTracker/UIs/Trackers/SecretTracker.xib, HSTracker/UIs/Trackers/TimerHud.swift, HSTracker/UIs/Trackers/TimerHud.xib, HSTracker/UIs/Trackers/Tracker.swift, HSTracker/UIs/Trackers/Tracker.xib
- Changed UI elements to stay on top of a full-screen Hearthstone game.
- Autopositioning trackers will be triggered when game enters/leaves fullscreen mode
=> Fullscreen overlay

HSTracker/AppDelegate.swift, HSTracker/UIs/Trackers/Tracker.swift
Also initial tracker positioning with multiple-screens should behave nicer.
=> Tracker disable bug fix

HSTracker.xcodeproj/project.pbxproj, HSTracker/HSTracker-Bridging-Header.h, HSTracker/UIs/DeckManager/Base.lproj/DeckManager.xib, HSTracker/UIs/DeckManager/Base.lproj/NewDeck.xib, HSTracker/UIs/DeckManager/CardCell.swift, HSTracker/UIs/DeckManager/DeckManager.swift, HSTracker/UIs/DeckManager/EditDeck.swift, HSTracker/UIs/DeckManager/GlowFilter.h, HSTracker/UIs/DeckManager/GlowFilter.m
Deck manager now accepts right click context menus, thus one can edit/rename/delete decks without first left-clicking them.
Class selection when creating a new deck is now select-only
Deck editor has now a fancy background color and chosen cards are now briefly flashed
=> Deckmanager pimp

HSTracker/Importers/Handlers/Hearthstonetopdecks.swift
Changed xpaths to match windows tracker: https://github.com/HearthSim/Hearthstone-Deck-Tracker/blob/master/Hearthstone%20Deck%20Tracker/Importing/Websites/Hearthstonetopdecks.cs
=> Fix hearthstonetopdecks.com importer

HSTracker/AppDelegate.swift, HSTracker/Database/Models/Card.swift, HSTracker/Database/Models/Deck.swift, HSTracker/Logging/Handlers/FullScreenFxHandler.swift, HSTracker/UIs/DeckManager/Base.lproj/SaveDeck.xib, HSTracker/UIs/DeckManager/SaveDeck.swift
Split deck version into a major and a minor integer value
Removed the possibility so specify the version of newly created / edited decks
Deck version will automatically get incremented as the player is swapping cards
=> Reworked deck versioning system

HSTracker/Database/Language.swift, HSTracker/HSReplay/ko-KR.lproj/HSReplayPreferences.strings, HSTracker/TrackOBot/ko-KR.lproj/TrackOBotLogin.strings, HSTracker/TrackOBot/ko-KR.lproj/TrackOBotPreferences.strings, HSTracker/UIs/DeckManager/ko-KR.lproj/DeckManager.strings, HSTracker/UIs/DeckManager/ko-KR.lproj/EditDeck.strings, HSTracker/UIs/DeckManager/ko-KR.lproj/NewDeck.strings, HSTracker/UIs/DeckManager/ko-KR.lproj/SaveDeck.strings, HSTracker/UIs/Preferences/en.lproj/TrackersPreferences.strings, HSTracker/UIs/Preferences/ko-KR.lproj/GamePreferences.strings, HSTracker/UIs/Preferences/ko-KR.lproj/GeneralPreferences.strings, HSTracker/UIs/Preferences/ko-KR.lproj/InitialConfiguration.strings, HSTracker/UIs/Preferences/ko-KR.lproj/OpponentTrackersPreferences.strings, HSTracker/UIs/Preferences/ko-KR.lproj/PlayerTrackersPreferences.strings, HSTracker/UIs/Preferences/ko-KR.lproj/Splashscreen.strings, HSTracker/UIs/Preferences/ko-KR.lproj/TrackersPreferences.strings, HSTracker/UIs/Preferences/ko-KR.lproj/UpdatePreferences.strings, HSTracker/UIs/StatsManager/ko-KR.lproj/LadderTab.strings, HSTracker/UIs/StatsManager/ko-KR.lproj/Statistics.strings, HSTracker/UIs/StatsManager/ko-KR.lproj/StatsTab.strings, HSTracker/UIs/ko-KR.lproj/MainMenu.strings, HSTracker/ko-KR.lproj/InfoPlist.strings, HSTracker/ko-KR.lproj/Localizable.strings, HSTrackerTests/ko-KR.lproj/InfoPlist.strings
I like Hearthstone and HSTracker.
I hope this helps Korean players enjoy hearthstone.
=> Add Korean translation.

HSTracker/Core/SizeHelper.swift, HSTracker/Logging/Handlers/TagChangeHandler.swift, HSTracker/Statistics/StatsHelper.swift, HSTracker/UIs/DeckManager/EditDeck.swift
I tried to run the project and ran into a lot of linting errros that wont let me build, solved them if they are of any help merge.
=> Fixing lint errors

HSTracker/HSReplay/zh-Hans.lproj/HSReplayPreferences.strings, HSTracker/TrackOBot/zh-Hans.lproj/TrackOBotLogin.strings, HSTracker/TrackOBot/zh-Hans.lproj/TrackOBotPreferences.strings, HSTracker/UIs/DeckManager/zh-Hans.lproj/DeckManager.strings, HSTracker/UIs/DeckManager/zh-Hans.lproj/EditDeck.strings, HSTracker/UIs/DeckManager/zh-Hans.lproj/NewDeck.strings, HSTracker/UIs/DeckManager/zh-Hans.lproj/SaveDeck.strings, HSTracker/UIs/Preferences/zh-Hans.lproj/GamePreferences.strings, HSTracker/UIs/Preferences/zh-Hans.lproj/GeneralPreferences.strings, HSTracker/UIs/Preferences/zh-Hans.lproj/OpponentTrackersPreferences.strings, HSTracker/UIs/Preferences/zh-Hans.lproj/PlayerTrackersPreferences.strings, HSTracker/UIs/Preferences/zh-Hans.lproj/TrackersPreferences.strings, HSTracker/UIs/Preferences/zh-Hans.lproj/UpdatePreferences.strings, HSTracker/UIs/StatsManager/zh-Hans.lproj/LadderTab.strings, HSTracker/UIs/StatsManager/zh-Hans.lproj/Statistics.strings, HSTracker/UIs/StatsManager/zh-Hans.lproj/StatsTab.strings, HSTracker/UIs/zh-Hans.lproj/MainMenu.strings, HSTracker/zh-Hans.lproj/Localizable.strings
We've just finished the Chinese tranlations (zh-Hans). @Psycho7
Thanks for your guide on the .strings files. @bmichotte
=> zh-hans translation

HSTracker/pt-BR.lproj/Localizable.strings
Added missing translations and performed minor fixes in existing ones
=> Improve translation for pt-BR language

HSTracker.xcodeproj/project.pbxproj, HSTracker/AppDelegate.swift, HSTracker/Core/Events.swift, HSTracker/Core/Settings.swift, HSTracker/Database/RealmHelper.swift, HSTracker/Logging/AppHealth.swift, HSTracker/Logging/CoreManager.swift, HSTracker/Logging/Game.swift, HSTracker/UIs/DeckManager/DeckManager.swift, HSTracker/UIs/DeckManager/EditDeck.swift, HSTracker/UIs/DeckManager/SaveDeck.swift, HSTracker/UIs/Preferences/Base.lproj/InitialConfiguration.xib, HSTracker/UIs/Preferences/InitialConfiguration.swift, HSTracker/UIs/StatsManager/LadderTab.swift, HSTracker/UIs/StatsManager/Statistics.swift, HSTracker/UIs/StatsManager/StatsTab.swift, HSTracker/UIs/Trackers/CardHud.swift, HSTracker/UIs/Trackers/CardList.swift, HSTracker/UIs/Trackers/Tracker.swift, HSTracker/UIs/Trackers/WindowManager.swift
Fixed preferences bugs on startup
Events and settings have own strings
Added deck manager to the dock
=> General fixes

HSTracker.xcodeproj/project.pbxproj, HSTracker/HSReplay/zh-Hant.lproj/HSReplayPreferences.strings, HSTracker/TrackOBot/zh-Hant.lproj/TrackOBotLogin.strings, HSTracker/TrackOBot/zh-Hant.lproj/TrackOBotPreferences.strings, HSTracker/UIs/DeckManager/zh-Hant.lproj/DeckManager.strings, HSTracker/UIs/DeckManager/zh-Hant.lproj/EditDeck.strings, HSTracker/UIs/DeckManager/zh-Hant.lproj/NewDeck.strings, HSTracker/UIs/DeckManager/zh-Hant.lproj/SaveDeck.strings, HSTracker/UIs/Preferences/zh-Hant.lproj/GamePreferences.strings, HSTracker/UIs/Preferences/zh-Hant.lproj/GeneralPreferences.strings, HSTracker/UIs/Preferences/zh-Hant.lproj/InitialConfiguration.strings, HSTracker/UIs/Preferences/zh-Hant.lproj/OpponentTrackersPreferences.strings, HSTracker/UIs/Preferences/zh-Hant.lproj/PlayerTrackersPreferences.strings, HSTracker/UIs/Preferences/zh-Hant.lproj/Splashscreen.strings, HSTracker/UIs/Preferences/zh-Hant.lproj/TrackersPreferences.strings, HSTracker/UIs/StatsManager/zh-Hant.lproj/LadderTab.strings, HSTracker/UIs/StatsManager/zh-Hant.lproj/Statistics.strings, HSTracker/UIs/StatsManager/zh-Hant.lproj/StatsTab.strings, HSTracker/UIs/zh-Hant.lproj/MainMenu.strings, HSTracker/zh-Hant.lproj/Localizable.strings
Translated to Traditional Chinese (zh-TW).
=> Localizable strings added.

CONTRIBUTING.md
Was missing this tiny detail when starting for the first time. Thanks!
=> Add instruction for getting latest card data

.travis.yml, HSTracker/Hearthstone/Secrets/SecretsManager.swift, HSTracker/Logging/LogLine.swift, HSTracker/Logging/Player.swift, HSTracker/Logging/PlayerTurn.swift, HSTracker/UIs/DeckManager/EditDeck.swift, HSTracker/UIs/StatsManager/StatsTab.swift
=> Adopt Swift 4.1 changes

HSTracker/Logging/Game.swift, HSTracker/Logging/Parsers/PowerGameStateParser.swift
Logs contain "UNKONWN HUMAN PLAYER" as of last patch
=> revert to using the mirror to get the opponent name

.travis.yml, HSTrackerTests/EnumTests.swift
=> Upped xcode version in .travis.yml to 10.1

HSTracker/UIs/Cards/CardBar.swift
Current behavior:
New behavior:
=> Bug Fix: Hero Cards gem not display

HSTracker/HSReplay/zh-Hans.lproj/HSReplayPreferences.strings, HSTracker/UIs/DeckManager/zh-Hans.lproj/DeckManager.strings, HSTracker/UIs/DeckManager/zh-Hans.lproj/EditDeck.strings, HSTracker/UIs/DeckManager/zh-Hans.lproj/NewDeck.strings, HSTracker/UIs/DeckManager/zh-Hans.lproj/SaveDeck.strings, HSTracker/UIs/Preferences/zh-Hans.lproj/GamePreferences.strings, HSTracker/UIs/Preferences/zh-Hans.lproj/GeneralPreferences.strings, HSTracker/UIs/Preferences/zh-Hans.lproj/OpponentTrackersPreferences.strings, HSTracker/UIs/Preferences/zh-Hans.lproj/PlayerTrackersPreferences.strings, HSTracker/UIs/Preferences/zh-Hans.lproj/TrackersPreferences.strings, HSTracker/UIs/StatsManager/zh-Hans.lproj/LadderTab.strings, HSTracker/UIs/StatsManager/zh-Hans.lproj/Statistics.strings, HSTracker/UIs/StatsManager/zh-Hans.lproj/StatsTab.strings, HSTracker/UIs/zh-Hans.lproj/MainMenu.strings
When I was using the latest version of HSTracker, I found that some of the content was still in English and was not translated. So I translated these content and optimized some other translations.
=> Optimize the Chinese (zh-Hans) translations

HSTracker/Hearthstone/Secrets/SecretsManager.swift
Fix secret helper for tracking these secrets:
1. Rat Trap
2. Hidden Wisdom
3. Never Surrender
=> Fix secret helper(#1065)

HSTracker/Hearthstone/Secrets/SecretsManager.swift, HSTrackerTests/SecretTests.swift
Rewrite the missing SecretTests, and also fix some secret helper code.
More secret unit tests are needed to be added.
=> Rewrite secret tests

.travis.yml, HSTracker/Core/Settings.swift, HSTracker/Logging/Enums/GameTag.swift, HSTracker/Logging/Game.swift, HSTracker/UIs/Preferences/Base.lproj/OpponentTrackersPreferences.xib, HSTracker/UIs/Preferences/Base.lproj/PlayerTrackersPreferences.xib, HSTracker/UIs/Preferences/OpponentTrackersPreferences.swift, HSTracker/UIs/Preferences/PlayerTrackersPreferences.swift, HSTracker/UIs/Trackers/Tracker.swift, HSTracker/UIs/Trackers/Tracker.xib
=> Add Galakrond invoke counter

HSTracker/Database/Cards.swift, HSTracker/Database/Database.swift, HSTracker/Database/Models/Card.swift, HSTracker/Logging/Enums/MultiClassGroup.swift
=> Fix multi-class handling in the deck builder

HSTracker/Core/Extensions/NSImage.swift, HSTracker/Core/SizeHelper.swift, HSTracker/Logging/Entity.swift, HSTracker/UIs/Trackers/CardHud.swift, HSTracker/UIs/Trackers/CardHudContainer.swift
=> Show creator images under hand icons

.gitignore, HSTracker/UIs/Views/BgHeroesToastView.swift, Translations/macOS/Base.lproj/Localizable.strings, Translations/macOS/de.lproj/Localizable.strings, Translations/macOS/es-MX.lproj/Localizable.strings, Translations/macOS/es.lproj/Localizable.strings, Translations/macOS/fr.lproj/Localizable.strings, Translations/macOS/it.lproj/Localizable.strings, Translations/macOS/ja.lproj/Localizable.strings, Translations/macOS/ko.lproj/Localizable.strings, Translations/macOS/pl.lproj/Localizable.strings, Translations/macOS/pt-BR.lproj/Localizable.strings, Translations/macOS/ru.lproj/Localizable.strings, Translations/macOS/th-TH.lproj/Localizable.strings, Translations/macOS/zh-Hans.lproj/Localizable.strings, Translations/macOS/zh-Hant.lproj/Localizable.strings, scripts/bootstrap.sh
Move translations back to HSTracker
=> Add available minions to Toast url

HSTracker/Core/SizeHelper.swift
=> Fix multi-desktop overlay for battlegrounds

Translations/macOS/ko.lproj/Localizable.strings
add korean translation for below
- naga
- mode_mercenaries
- on top
- on bottom
=> Add korean translation

Translations/macOS/ko.lproj/Localizable.strings
=> Add korean translation for placement text

HSTracker/AppDelegate.swift, HSTracker/HSReplay/HSReplayPreferences.swift, Translations/macOS/Base.lproj/Localizable.strings
=> feat: track and display username from oAuth login
