app/controllers/manager/deck_manager.rb

Validate search string to prevent empty results. Similar to line 200 in c12921b5edbfb6b5fae2c8c90a9a247e1b4ca850
Without this, the user will see empty results if he uses backspace to clear the search field.

Validate search string to prevent empty results

---

HSTracker/Info.plist
HSTracker/UIs/Trackers/Tracker.swift

Currently, the "hand chance" field of the opponent tracker shows basically "100 / (number of cards in hand)", which I think is not particularly useful for anything. This patch changes it to show the probability they have a certain card, when they have either one or two of them left unplayed (useful for e.g. knowing the chance the opponent can C'Thun next turn). This is what HDT also does.

Change opponent tracker to show their chances of having a particular card

---

HSTracker/Hearthstats/Base.lproj/HearthstatsLogin.xib
HSTracker/Hearthstats/HearthstatsLogin.swift

Improves the UI feedback while logging into Hearthstats from within the
app:
* While authentication is in-flight, disable the login form and show a
progress indicator.
* Make the “Login” button the default button so hitting enter will start
authentication.
* After successful authentication, let the `loadDecks` call complete
before showing the “login succeeded” alert. Previously, the user would
see the “login succeeded” alert, but after dismissing it, the login
screen would remain visible for a few seconds while `loadDecks`
completed, but it was unclear to the user that anything was happening.
This cleans up that interaction to prevent the user from interacting
with the UI until everything has completed.

Improve UI feedback during Hearthstats login

---

HSTracker/UIs/DeckManager/EditDeck.swift

**Motivation:**
Often building arena decks, and my workflow is currently:
1. press ⌘+F
2. type first few chars of the card until there are only few cards (ideally just one) on the screen so that it is easily spotted in the few
3. click on the card
4. goto step 1.
The switch between keyboard for filtering cards and mouse for selecting one of the few cards left after filtering is annoying me :D
<hr>
**Solution:**
Implemented keyboard shortcuts ⌘-[1 to 9], where the number is the position of the first 9 cards in the grid view (counting from left to right including wrapping around). This allows for the following flow:
1. press ⌘+F
2. type first few chars of the card until there are only few cards (ideally just one) on the screen so that it is easily spotted in the few
3. seeing the card I …

Deck Manager (editor) - keyboard shortcuts for adding a card to the deck

---

HSTracker/UIs/DeckManager/EditDeck.swift

I'm not sure if this was designed like this, but if you're editing multiple decks (possibly of the same class), it's not completely easy to figure out what deck you're editing.
Showing the name of the deck seems like a really easy fix

Show the name of the deck when you're editing it

---

HSTracker/AppDelegate.swift
HSTracker/Database/Models/Deck.swift
HSTracker/Database/Models/Decks.swift
HSTracker/UIs/DeckManager/Base.lproj/DeckManager.xib
HSTracker/UIs/DeckManager/DeckManager.swift

Here's a simple patch that allows the user to "Archive" a deck. All it does is set a flag on the deck itself so it gets filtered differently than normal decks.
I've set the isArchived to be an optional so it doesn't affect Unboxer. (I'm not sure how unboxer works, but if I did isArchived: Bool = false, Unboxer would fail to initialize it because of the unrecognized key). I figured leaving this as an optional means that the DB doesn't need to be updated with this key per deck. It should "just work"

Ability to archive/unarchive deck

---

HSTracker/UIs/DeckManager/DeckManager.swift

Few bugs I found while using the app:
1. If you select a filter (say, Druid), select a deck, filter Druid again, the table view does not get updated
Fix: Check if you have a current deck already selected before setting currentClass to nil. Since refreshDecks() is called whenever we select a filter, it will properly deselect the current selected deck. 
2. If you select a filter with fewer decks than the next filter, the new filter doesn't get applied.
Issue: Since we deselect all decks when selecting a filter, tableViewSelectionDidChange gets called on the old filter as well as the new filter, so there is an issue with row selection.
Fix: Make sure in tableViewSelectionDidChange that we are modifying the new filter and not the old
3. I was hitting some crashes when quickly selecting decks …

This pull request fixes some bugs when doing class filters

---

HSTracker/Logging/Game.swift
HSTracker/Logging/Player.swift

Don't reset player ID if you're in a game and you set a deck.
This fixes the issue here:
https://github.com/bmichotte/HSTracker/issues/459

Don't reset player id when in a game and swapping decks

---

.travis.yml

Fixed missing `-` in travis.yml file
Used http://lint.travis-ci.org/ to lint the travis file.
Test should now output something significant instead of
`ERROR: An error occured while trying to parse your .travis.yml file.`
P.S:
just out of curiosity, is there a reason why `CODE_SIGNING_REQUIRED=NO` is done twice?

Fix syntax errors in travis.yml

---

HSTracker/UIs/DeckManager/DeckManager.swift

Removed the .action of the tableView and just used tableViewSelectionDidChange, which also gets called on arrow up selection.

Fixed arrow key interaction with table view

---

HSTracker/Database/ImageDownloader.swift

On launch, we check if any card images are missing and mark them for download. This PR also checks that the image can be loaded, and marks corrupt images for download. This appears to add less than 1 second of overhead on launch.
Hopefully, this will prevent future issues like #518.

Check if images are corrupt on launch and redownload

---

HSTracker.xcodeproj/project.pbxproj
HSTracker/Logging/Game.swift
HSTracker/Utility/ImageUtilities.swift
HSTracker/Utility/RankDetection/CVRankDetection.swift
HSTracker/Utility/RankDetection/CVRankDetector.cpp
HSTracker/Utility/RankDetection/CVRankDetector.hpp

1. Rank detection now returns "nil" when confidence is below a threshold (suggested by @bmichotte). This allows us to determine whether a game is "Casual" or "Ranked" based on whether we can find ranks in the window.
2. Tightened cropping window around rank icons. This should improve accuracy when the game window is very small. This will also improve performance.
3. Increased the allowed difference between player and opponent rank for a game to still be categorized as "Ranked". This is because rank gaps can be large at the beginning of the season or in Wild mode.
These improvements, coupled to the previous rank detection improvements should (hopefully) close a number of issues, including #514, #487, #442, #434 (partially), #415, and #406.

Three improvements to rank detection

---

HSTracker/Base.lproj/Localizable.strings
HSTracker/Database/Models/Deck.swift
HSTracker/Logging/Enums/GameMode.swift
HSTracker/Statistics/StatsHelper.swift
HSTracker/UIs/DeckManager/DeckManager.swift
HSTracker/UIs/StatsManager/Base.lproj/Statistics.xib
HSTracker/UIs/StatsManager/Statistics.swift
HSTracker/UIs/Trackers/Tracker.swift
HSTracker/de.lproj/Localizable.strings
HSTracker/es.lproj/Localizable.strings
HSTracker/fr.lproj/Localizable.strings
HSTracker/it.lproj/Localizable.strings
HSTracker/pt-BR.lproj/Localizable.strings
HSTracker/zh-Hans.lproj/Localizable.strings

Four fixes to how stats are computed and displayed:
1. Only ranked games are shown
2. Fixed capitalization of class names in stats window
3. Cleaned up internals of StatsHelper
4. DeckManager and record tracker get stats from StatsHelper instead of Deck (put all stat handling in one place)

Cleanup stats

---

HSTracker/Core/SizeHelper.swift

I'm not sure if this is retina only. Because it was slightly off screen without it.

Move the secret tracker so slightly. Picture attached

---

HSTracker.xcodeproj/project.pbxproj
HSTracker/HSTracker-Bridging-Header.h
HSTracker/Logging/Hearthstone.swift
HSTracker/Logging/LogReader.swift
HSTracker/Logging/LogReaderManager.swift
HSTracker/Utility/FileUtils.h
HSTracker/Utility/FileUtils.m

Initial logfile offset was not calculated properly as HSTracker was unable to erase the log files when needed.
The root cause of the issue was that
1, LogReader was checking for a running game instance, but it was always true as this check was run after the game was launched. This was probably the result of the circular dependency between the Hearthstone singleton and a LogReader instance. This PR unwinds this dependency.
2, Unlike under Windows, it is possible to delete log files while the game is actively using them. A proper check has been implemented to be sure if the logs are free for deletion.

Fixed random tracking problem

---

HSTracker/UIs/DeckManager/DeckManager.swift

Hey, 
I thought it was pretty annoying that all rows in the DeckManager are highlighted as a default, so
here is a pretty sophisticated change to solve that...

[FIX] Removed default all rows highlight.

---

HSTracker/Database/Models/GameStats.swift

So apparently the stats were not displaying correctly, because there was no information
on the gameMode and opponentHero passed. I changed that, although I am not sure if 
this is the way it is supposed to work. Whatever, here is a PR fixing the stats screen for
me.

[FIX] Copy gameMode and opponentHero to fix stats.

---

HSTracker/UIs/Cards/CardBar.swift

As seen above, Rares are darkened after two copies are added.
Legendaries should darken after one copy is added.

Bug Fix: In deck builder, legendaries are darkened after adding one copy to a non-arena deck

---

HSTracker/ArenaHelper/ArenaWatcher.swift

Cards that are bad in multiples are marked with "*" in the json, not "^"
Fixes #877

Check for "*" instead of "^"

---

Dangerfile

Current Dangerfile fail to detect if changes are made for `Info.plist` file. 
e.g. #967 includes no changes to `Info.plist` but Danger stills showed warning.

Fix Danger check for Info.plist

---

.travis.yml

#951 introduced a new CI lane which prepares CI environment, build Carthage packages, and finally Xcode test. However, it wasn't really used after all and thereafter breaks recent CI builds.

Use correct fastlane lane for CI

---

HSTracker/UIs/Trackers/FloatingCard.swift

Set FloatingCard's text color using the `textColor` variable instead of hardcoding it to `black` so the text shows up on both light and dark modes' backgrounds.
Before:
After:

Make FloatingCard text readable for OSX dark mode

---

HSTracker/Core/Settings.swift
HSTracker/UIs/Cards/CardBar.swift
HSTracker/UIs/Cards/ClassicBar.swift

When the user sets the language to Chinese (zh-Hans), the official font of Heatrhstone is called `JingDianLiBianJian`. But currently HSTracker is using font `NanumGothic`, and it looks strange:
This pull request changes the font of language zh-Hans. The new behavior:

Optimize the Chinese font displaying

---

HSTracker/HSReplay/HSReplayManager.swift

This commit changes the replay URL domain from api.hsreplay.net to hsreplay.net.

Fix replay url domain

---

HSTracker/Hearthstone/Secrets/SecretsManager.swift
HSTracker/Logging/CardIds/Neutral.swift
HSTracker/Logging/CardIds/Warrior.swift
HSTracker/Logging/Parsers/PowerGameStateParser.swift

Additional bombs triggered by Augmented Elekk are now tracked correctly.
Also, I notice that Block.cardId is assigned with a value of the format like "cardId=DAL_060" when a new Block is created. I suppose it makes more sense if it is assigned with a value like "DAL_060" rather than "cardId=DAL_060", based on the whole code logic. Let me know if I understand it wrong.

Fix Augmented Elekk bomb tracking(#1050)

---

HSTracker/Hearthstone/Secrets/SecretsManager.swift
HSTrackerTests/SecretTests.swift

Fix the issue(#972 and #994) of secret helper causing HSTracker lag.
To reproduce the problem:
1. The opponent has at least one active secret and at least two minions on board
2. The player kills one of the opponent's minions
3. HSTracker will freeze completely for around 50 seconds

Fix secret helper causing lag(#972, #994)

---

HSTracker/Hearthstone/Secrets/SecretsManager.swift
HSTracker/Logging/Enums/GameTag.swift
HSTracker/Logging/Game.swift
HSTracker/Logging/Handlers/LogEventHandlers.swift
HSTracker/Logging/Parsers/TagChangeActions.swift
HSTracker/UIs/Trackers/TimerHud.swift
HSTracker/UIs/Trackers/TimerHud.xib
HSTrackerTests/SecretTests.swift

1. Now when the last played minion died after explosive trap or snipe, other secrets still display
2. Add unit tests for that
3. Keep secrets sorted, to prevent them from always changing positions even no secret is triggered or faded out

Fix secret handling when minion dies

---

HSTracker/Logging/CardIds/Priest.swift
HSTracker/Logging/Parsers/PowerGameStateParser.swift
HSTracker/Logging/Player.swift

Trackers are now able to track those card copies generated by 'Spirit of the Dead' correctly, for both the player and the opponent.

Fix cards tracking for Spirit of the Dead

---

HSTracker/UIs/Trackers/Tracker.swift

Currently, the probability of an opponent having a card is computed by assuming that the card is placed randomly in either the opponents hand or deck. This is not really an accurate predictor as to if the opponent has drawn the card or not. 
Consider the following example:
The opponent has 3 cards in hand and 11 cards in their deck. Assuming they haven't shuffled any additional cards into their deck, and haven't added any cards (except for maybe the original coin) to their hand, the existing algorithm would compute the probability as follows:
if running one of: 28.57% chance in hand
if running two of: 50.55% chance in hand
While the proposed change would compute these probabilities instead:
Computed 1:  66.66%
Computed 2:  89.65%
This makes more sense. If the opponent has drawn 2/3 of …

Fix probabilities for opponent having a card in hand

---

scripts/release.kts
scripts/release.main.kts

With jcenter going down, kinta was not available anymore. I forked it under `net.mbonnin` until https://github.com/dailymotion/kinta/issues/39 is resolved.

Release scripts: use a kinta fork for now

---

HSTracker/UIs/Preferences/zh-Hans.lproj/BattlegroundsPreferences.strings
HSTracker/UIs/Preferences/zh-Hans.lproj/OpponentTrackersPreferences.strings
HSTracker/UIs/Preferences/zh-Hans.lproj/PlayerTrackersPreferences.strings
HSTracker/UIs/Preferences/zh-Hans.lproj/TrackersPreferences.strings
HSTracker/UIs/zh-Hans.lproj/MainMenu.strings
Translations/macOS/zh-Hans.lproj/Localizable.strings

Improve zh-Hans translations.
By the way, why `MercenariesPreferences.xib` is in `HSTracker/UIs/Preferences/HSTracker/UIs/Preferences/Base.lproj` other than `HSTracker/UIs/Preferences/Base.lproj`? And no local strings for it. Is this a mistake?

Improve zh-Hans translations

---

HSTracker/Logging/Game.swift

Resolve #1263 
I fixed the bug "BattlegroundsSession can not be seen in game modes."
Now, it can be seen in game modes as below.
**FYI**.
I already checked this change does not effect other modes. It means BattlegroundsSession is not shown when people play other game modes.

Fix session recap not showing in BG modes

---

HSTracker/Logging/CardIds/Hunter.swift

The Secret tracker overlay was not tracking the new Core set version of Wandering Monster in Standard ranked games.
This commit adds it's ID to the list of secrets.

Add Core set Wandering Monster to secret list

---

HSTracker/HSReplay/HSReplay.swift

This endpoint is moving from `/quest_stats/` to `/quest_pick/`.

feat: update quest stats URL
